name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          debug: true
          script: |
            eval "$(ssh-agent -s)"                          # Start SSH agent
            ssh-add ~/.ssh/id_rsa_github                    # Add GitHub key
            cd /home/ec2-user/oumli-api                     # Go to app directory
            git pull origin master                          # Pull latest changes
            npm install                                     # Install dependencies
            pm2 restart node-app                            # Restart app
