name: Test SSH Connection to EC2

on:
  push:
    branches:
      - master # This will trigger the action when code is pushed to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }} # The EC2 public IP from GitHub secrets
          username: ${{ secrets.EC2_USER }} # Typically 'ec2-user'
          key: ${{ secrets.EC2_KEY }} # The private key from GitHub secrets
          port: 22
          debug: true
          script: echo "SSH connection successful!"
