name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Build project
        run: npm run build

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }} # EC2 public IP or domain (e.g., production.api.oumli.com)
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          debug: true
          script: |
            cd /path/to/your/app                 # Replace with the path to your app on EC2
            git pull origin master               # Pull the latest changes from GitHub
            npm install                          # Install new dependencies
            pm2 restart node-app                 # Restart your Node.js app using PM2
